backend:
  name: github
  repo: SharepointDesigns/documentation
  branch: Deploy-Automate
  base_url: https://spdproductdocs-e3epgcb4dvcwasdy.centralindia-01.azurewebsites.net
  auth_type: implicit
  auth_endpoint: /api/auth
  token_endpoint: /api/callback
  # Uncomment when running locally
# local_backend: true

publish_mode: editorial_workflow
media_folder: "/spd-documentation/static/img/uploads"
public_folder: "uploads"
show_preview_links: true
editor:
  preview: true

# Site URL for previews
site_url: https://sharepointdesigns.github.io/documentation
logo:
  src: https://sharepointdesigns.github.io/documentation/img/spdlogo.svg
  alt: Sharepoint Designs
  show_in_header: true

collections:
  # Main Documentation Pages
  - name: "docs"
    label: "Main Documentation"
    folder: "spd-documentation/docs"
    create: true
    slug: "{{slug}}"
    media_folder: "/spd-documentation/static/img/uploads"
    public_folder: "/img/uploads"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  # Design 1 Documentation (Parent)
  - name: "design-1"
    label: "Design 1"
    label_singular: "Design 1 Doc"
    folder: "spd-documentation/docs/design-1"
    create: true
    format: frontmatter
    extension: "md"
    slug: "{{slug}}"
    media_folder: "/spd-documentation/docs/design-1/assets"
    public_folder: "assets"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  # Design 1 Subpages (Nested under Design 1)
  - name: "design-1-subpages"
    label: "└─ Design 1 Subpages"
    label_singular: "Design 1 Subpage"
    folder: "spd-documentation/docs/design-1/design-1-subpages"
    media_folder: "/spd-documentation/docs/design-1/design-1-subpages/assets"
    public_folder: "assets"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  # Design 2 Documentation (Parent)
  - name: "design-2"
    label: "Design 2"
    label_singular: "Design 2 Doc"
    folder: "spd-documentation/docs/design-2"
    create: true
    format: frontmatter
    extension: "md"
    media_folder: "/spd-documentation/docs/design-2/assets"
    public_folder: "assets"
    slug: "{{slug}}"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  # Design 2 Subpages (Nested under Design 2)
  - name: "design-2-subpages"
    label: "└─ Design 2 Subpages"
    label_singular: "Design 2 Subpage"
    folder: "spd-documentation/docs/design-2/design-2-subpages"
    media_folder: "/spd-documentation/docs/design-2/design-2-subpages/assets"
    public_folder: "assets"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  # Design 3 Documentation (Parent)
  - name: "design-3"
    label: "Design 3"
    label_singular: "Design 3 Doc"
    folder: "spd-documentation/docs/design-3"
    create: true
    format: frontmatter
    extension: "md"
    media_folder: "/spd-documentation/docs/design-3/assets"
    public_folder: "assets"
    slug: "{{slug}}"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  # Design 4 Documentation
  - name: "design-4"
    label: "Design 4 Docs"
    folder: "spd-documentation/docs/design-4"
    media_folder: "/spd-documentation/docs/design-4/assets"
    public_folder: "assets"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  # Design 5 Documentation
  - name: "design-5"
    label: "Design 5 Docs"
    folder: "spd-documentation/docs/design-5"
    create: true
    media_folder: "/spd-documentation/docs/design-5/assets"
    public_folder: "assets"
    slug: "{{slug}}"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  # Employee Onboarding Documentation
  - name: "employee-onboarding"
    label: "Employee Onboarding Docs"
    folder: "spd-documentation/docs/employee-onboarding"
    create: true
    media_folder: "/spd-documentation/docs/employee-onboarding/assets"
    public_folder: "assets"
    slug: "{{slug}}"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  # Free Template Documentation
  - name: "free-template"
    label: "Free Template Docs"
    folder: "spd-documentation/docs/free-template"
    create: true
    media_folder: "/spd-documentation/docs/free-template/assets"
    public_folder: "assets"
    slug: "{{slug}}"
    sortable_fields: ["sidebar_position", "title"]
    sort:
      field: "sidebar_position"
      direction: "asc"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Sidebar Position",
          name: "sidebar_position",
          widget: "number",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  # Blog Posts
  # - name: "blog"
  #   label: "Blog"
  #   folder: "blog"
  #   create: true

  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Author", name: "authors", widget: "list", allow_add: true }
  #     - { label: "Tags", name: "tags", widget: "list", required: false }
  #     - { label: "Body", name: "body", widget: "markdown" }

  # Category Configuration Files
  - name: "categories"
    label: "Category Settings"
    files:
      - label: "Design 1 Category"
        name: "design-1-category"
        file: "spd-documentation/docs/design-1/_category_.json"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Position", name: "position", widget: "number" }
          - {
              label: "Link Type",
              name: "link.type",
              widget: "select",
              options: ["generated-index", "doc"],
              required: false,
            }
          - {
              label: "Link Description",
              name: "link.description",
              widget: "text",
              required: false,
            }

      - label: "Design 1 Subpages Category"
        name: "design-1-subpages-category"
        file: "spd-documentation/docs/design-1/design-1-subpages/_category_.json"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Position", name: "position", widget: "number" }
          - {
              label: "Link Type",
              name: "link.type",
              widget: "select",
              options: ["generated-index", "doc"],
              required: false,
            }
          - {
              label: "Link Description",
              name: "link.description",
              widget: "text",
              required: false,
            }

      - label: "Design 2 Category"
        name: "design-2-category"
        file: "spd-documentation/docs/design-2/_category_.json"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Position", name: "position", widget: "number" }
          - {
              label: "Link Type",
              name: "link.type",
              widget: "select",
              options: ["generated-index", "doc"],
              required: false,
            }
          - {
              label: "Link Description",
              name: "link.description",
              widget: "text",
              required: false,
            }

      - label: "Design 2 Subpages Category"
        name: "design-2-subpages-category"
        file: "spd-documentation/docs/design-2/design-2-subpages/_category_.json"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Position", name: "position", widget: "number" }
          - {
              label: "Link Type",
              name: "link.type",
              widget: "select",
              options: ["generated-index", "doc"],
              required: false,
            }
          - {
              label: "Link Description",
              name: "link.description",
              widget: "text",
              required: false,
            }

      - label: "Design 4 Category"
        name: "design-4-category"
        file: "spd-documentation/docs/design-4/_category_.json"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Position", name: "position", widget: "number" }
          - {
              label: "Link Type",
              name: "link.type",
              widget: "select",
              options: ["generated-index", "doc"],
              required: false,
            }
          - {
              label: "Link Description",
              name: "link.description",
              widget: "text",
              required: false,
            }

      - label: "Design 5 Category"
        name: "design-5-category"
        file: "spd-documentation/docs/design-5/_category_.json"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Position", name: "position", widget: "number" }
          - {
              label: "Link Type",
              name: "link.type",
              widget: "select",
              options: ["generated-index", "doc"],
              required: false,
            }
          - {
              label: "Link Description",
              name: "link.description",
              widget: "text",
              required: false,
            }

      - label: "Employee Onboarding Category"
        name: "employee-onboarding-category"
        file: "spd-documentation/docs/employee-onboarding/_category_.json"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Position", name: "position", widget: "number" }
          - {
              label: "Link Type",
              name: "link.type",
              widget: "select",
              options: ["generated-index", "doc"],
              required: false,
            }
          - {
              label: "Link Description",
              name: "link.description",
              widget: "text",
              required: false,
            }

      - label: "Free Template Category"
        name: "free-template-category"
        file: "spd-documentation/docs/free-template/_category_.json"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Position", name: "position", widget: "number" }
          - {
              label: "Link Type",
              name: "link.type",
              widget: "select",
              options: ["generated-index", "doc"],
              required: false,
            }
          - {
              label: "Link Description",
              name: "link.description",
              widget: "text",
              required: false,
            }
