name: Deploy Documentation

on:
  push:
    branches:
      - Deploy-Automate

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: spd-documentation/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: spd-documentation

      - name: Build
        run: npm run build
        working-directory: spd-documentation

      - name: Deploy to GitHub Pages
        working-directory: spd-documentation
        env:
          GIT_USER: github-actions[bot] # Git author for commits
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          GH_TOKEN: ${{ secrets.PAT_TOKEN }} # Your Personal Access Token
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # Ensure the remote URL uses the token for authentication
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # Run Docusaurus deploy
          npx docusaurus deploy
