name: Deploy Documentation

on:
  push:
    branches:
      - Test-Deploy

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: spd-documentation/package-lock.json

      - name: Setup Git identity
        run: |
          git config --global user.name "sharepointdesigns"
          git config --global user.email "github-actions@sharepointdesigns.com"

      - name: Install dependencies
        run: npm install
        working-directory: spd-documentation

      - name: Build
        run: npm run build
        working-directory: spd-documentation

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: spd-documentation/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
