name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: spd-documentation/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: spd-documentation

      - name: Build
        run: npm run build
        working-directory: spd-documentation

      - name: Deploy
        run: npm run deploy
        working-directory: spd-documentation
